### ISSUE TITLE
Bot doesn't respond to any commands.

### ISSUE THREAD

**Issue by warlocc** [matsyui/PruneBot#6]
pb !
pb!
!pb
pb help!
/pb
/ pb!
/ !pb
/pb help
!pb help

Nothing works.

**Comment by mashwishi** [comment]
The default command prefix is `pb!` for help is `pb!help` to change the prefix `pb!setprefix <prefix>`

If you forked this project, prefix can be found at:
https://github.com/mashwishi/PruneBot/blob/master/config/config.json
https://github.com/mashwishi/PruneBot/blob/master/config/settings.json
